### ISSUE TITLE
1.0.0-3.0.2 should use the STD_PKG2 data

### ISSUE THREAD

**Issue by JamePeng** [dennthecafebabe/vaporware#1]
bis.py 

error:    
self.safe_pkg_bct_bytes, self.safe_pkg_pkg1_bytes, self.safe_pkg_pkg2_bytes         = self.safe_pkg_nca.bis_bytes(tempdir="./temp", platform=self.ctx.version_ctx[1].lower())
AttributeError: 'NoneType' object has no attribute 'bis_bytes'

fix:
       # 1.0.0 - 3.0.2 exFAT workaround
        if self.ctx.version_ctx[0] <= "3.0.2.0":
            self.normal_pkg_tid = STD_PKG2[0]
            self.safe_pkg_tid = STD_PKG2[1]

**Comment by dennthecafebabe** [comment]
Thanks for the fix. Vaporware is kinda deprecated though and i would personally recommend anyone to use [this](https://github.com/suchmememanyskill/EmmcHaccGen) instead - it uses LibHac and should be way less error-prone than my thing.

**Comment by JamePeng** [comment]
I think this project is the nice rewrite of ChoiDujour with python3, :P
And I tested all version firmware and it was working fine at all !
Good job, dennthecafebabe

**Comment by dennthecafebabe** [comment]
Thanks a lot for the kind words, really means a lot to me.
